### ISSUE TITLE
triangle fill function stops drawing too early on some triangles.

### ISSUE THREAD

**Issue by Vili-Valtteri** [oskarikinnunen/DoomNukem#5]
(in vlaine branch)
z_fill_tri function doesn't always draw the last index for the triangle leaving empty pixels.

This could be due to rounding float to int or just ending the while loop too early.

Potential fixes: 
1. Check that the float to int conversion always rounds up or down.
2. Check that z_fill_tri while loop, loops the correct amount of times.

(Linked image, where wall is missing few pixels.)
<img width="357" alt="Screen Shot 2022-10-14 at 11 10 12 AM" src="https://user-images.githubusercontent.com/86079441/195799355-05c7412f-b24c-4bfb-ad8d-c8cae5827e57.png">

**Comment by oskarikinnunen** [comment]
Fixed with the new filltriangle in main branch.
